# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2422b389cd380b64dbc04c303ab96cc541a1798404d1e8e242d8de7d7be079e7d3e181f9c4dc062391a8307aaf04b50172df52bf82b79e43cd8733b54ec00e7e

test:
  secret_key_base: 2b1144d723d22409716159624128555caec613974402510f20e63eeed3590021e4da1abde4508cdfc7c0aa8c450822f86cf5999d0534cdbb2b360dbc8168c700

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
